# Generated by Django 4.0.6 on 2022-08-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVTEmilio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=54)),
                ('edad', models.IntegerField()),
                ('documento', models.IntegerField()),
                ('fecha_nacimiento', models.CharField(max_length=20)),
                ('parentezco', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Madre',
        ),
    ]
